/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface C06u1uquy7p {
        "first": string;
        "second": string;
    }
    interface C07lxad0658 {
        "first": string;
        "second": string;
    }
    interface C0zolhns0tt {
        "first": string;
        "second": string;
    }
    interface C1gfk4e7z6v {
        "first": string;
        "second": string;
    }
    interface C1zwn4ylwkg {
        "first": string;
        "second": string;
    }
    interface C2jdap6s83q {
        "first": string;
        "second": string;
    }
    interface C2l9zhv6s9j {
        "first": string;
        "second": string;
    }
    interface C372kixrse8 {
        "first": string;
        "second": string;
    }
    interface C3b9k908rpk {
        "first": string;
        "second": string;
    }
    interface C3erd4s9c5m {
        "first": string;
        "second": string;
    }
    interface C3fxlqqoa1n {
        "first": string;
        "second": string;
    }
    interface C3in4zcw4ir {
        "first": string;
        "second": string;
    }
    interface C41k1do1hz9 {
        "first": string;
        "second": string;
    }
    interface C4ec5vavagn {
        "first": string;
        "second": string;
    }
    interface C4fbygxj908 {
        "first": string;
        "second": string;
    }
    interface C4y3ufy0vqz {
        "first": string;
        "second": string;
    }
    interface C5a0ubhr3nf {
        "first": string;
        "second": string;
    }
    interface C5cgko9z7rs {
        "first": string;
        "second": string;
    }
    interface C5fluomxfua {
        "first": string;
        "second": string;
    }
    interface C5gzkl3ag53 {
        "first": string;
        "second": string;
    }
    interface C624g6590jz {
        "first": string;
        "second": string;
    }
    interface C6rlfmr7imi {
        "first": string;
        "second": string;
    }
    interface C7tix3ilvdy {
        "first": string;
        "second": string;
    }
    interface C8q2higyiy1 {
        "first": string;
        "second": string;
    }
    interface C8z9htpdbrc {
        "first": string;
        "second": string;
    }
    interface C9h0bigfpss {
        "first": string;
        "second": string;
    }
    interface C9jv0q451du {
        "first": string;
        "second": string;
    }
    interface C9mzb3ftkci {
        "first": string;
        "second": string;
    }
    interface CArbrgx9up2 {
        "first": string;
        "second": string;
    }
    interface CAu912e51tt {
        "first": string;
        "second": string;
    }
    interface CBqgp5mgr24 {
        "first": string;
        "second": string;
    }
    interface CBzkrwx38iy {
        "first": string;
        "second": string;
    }
    interface CBzn7pzxw81 {
        "first": string;
        "second": string;
    }
    interface CC75lozb961 {
        "first": string;
        "second": string;
    }
    interface CC7c5t54urq {
        "first": string;
        "second": string;
    }
    interface CD7k6npd91e {
        "first": string;
        "second": string;
    }
    interface CDg1o6hvgmh {
        "first": string;
        "second": string;
    }
    interface CDg3pa9wx90 {
        "first": string;
        "second": string;
    }
    interface CDw5fah0dak {
        "first": string;
        "second": string;
    }
    interface CEa6dkc7txr {
        "first": string;
        "second": string;
    }
    interface CEsoi0j8qe9 {
        "first": string;
        "second": string;
    }
    interface CG9ehgvurfl {
        "first": string;
        "second": string;
    }
    interface CGxdiszlvbr {
        "first": string;
        "second": string;
    }
    interface CHynos1l9j1 {
        "first": string;
        "second": string;
    }
    interface CI3u6qvb857 {
        "first": string;
        "second": string;
    }
    interface CImh9k2bdv0 {
        "first": string;
        "second": string;
    }
    interface CImtn3aobsi {
        "first": string;
        "second": string;
    }
    interface CIrlw1y0vnn {
        "first": string;
        "second": string;
    }
    interface CIsmiutkdb3 {
        "first": string;
        "second": string;
    }
    interface CJdqsj6bhuf {
        "first": string;
        "second": string;
    }
    interface CJhossdpdsa {
        "first": string;
        "second": string;
    }
    interface CKjuy16vwnh {
        "first": string;
        "second": string;
    }
    interface CKxgdbgnyig {
        "first": string;
        "second": string;
    }
    interface CKyhxkza3bj {
        "first": string;
        "second": string;
    }
    interface CMac32hasu5 {
        "first": string;
        "second": string;
    }
    interface CMhxod1mfr1 {
        "first": string;
        "second": string;
    }
    interface CMyiojn1a6d {
        "first": string;
        "second": string;
    }
    interface CN58v98xjdj {
        "first": string;
        "second": string;
    }
    interface CN7a4ihuwat {
        "first": string;
        "second": string;
    }
    interface CNazayymwp9 {
        "first": string;
        "second": string;
    }
    interface CNl8zpsalid {
        "first": string;
        "second": string;
    }
    interface CNor5t0g9do {
        "first": string;
        "second": string;
    }
    interface CNtciy01o41 {
        "first": string;
        "second": string;
    }
    interface COdvbf8zr05 {
        "first": string;
        "second": string;
    }
    interface CPma0x0hadn {
        "first": string;
        "second": string;
    }
    interface CPpqmrgr9ur {
        "first": string;
        "second": string;
    }
    interface CQ8olsms93h {
        "first": string;
        "second": string;
    }
    interface CQr0nl8jymd {
        "first": string;
        "second": string;
    }
    interface CR77lnek7x1 {
        "first": string;
        "second": string;
    }
    interface CRda8pdtf5u {
        "first": string;
        "second": string;
    }
    interface CRkzbq12k0v {
        "first": string;
        "second": string;
    }
    interface CRuweknhd3a {
        "first": string;
        "second": string;
    }
    interface CS9tevpt81q {
        "first": string;
        "second": string;
    }
    interface CSc5u2i9fzd {
        "first": string;
        "second": string;
    }
    interface CSp4ik5bs8n {
        "first": string;
        "second": string;
    }
    interface CSv84ghh89r {
        "first": string;
        "second": string;
    }
    interface CTlafahtx59 {
        "first": string;
        "second": string;
    }
    interface CTp8smsoy1t {
        "first": string;
        "second": string;
    }
    interface CTqm40gnm29 {
        "first": string;
        "second": string;
    }
    interface CTz8loest3z {
        "first": string;
        "second": string;
    }
    interface CU24qr34bli {
        "first": string;
        "second": string;
    }
    interface CU4yltmxd3a {
        "first": string;
        "second": string;
    }
    interface CU5oftmd61c {
        "first": string;
        "second": string;
    }
    interface CUg8k83hoie {
        "first": string;
        "second": string;
    }
    interface CVgp19gz1il {
        "first": string;
        "second": string;
    }
    interface CVnn1j1of74 {
        "first": string;
        "second": string;
    }
    interface CWa1wjxh046 {
        "first": string;
        "second": string;
    }
    interface CWjoi1mwbs1 {
        "first": string;
        "second": string;
    }
    interface CWn1p2nu3d5 {
        "first": string;
        "second": string;
    }
    interface CWursvokoqd {
        "first": string;
        "second": string;
    }
    interface CXfj5pfjbzw {
        "first": string;
        "second": string;
    }
    interface CXm3sieu2i4 {
        "first": string;
        "second": string;
    }
    interface CXvb7s33ex4 {
        "first": string;
        "second": string;
    }
    interface CXw6voqzmdo {
        "first": string;
        "second": string;
    }
    interface CXxcxappzlc {
        "first": string;
        "second": string;
    }
    interface CYbsjy24fs9 {
        "first": string;
        "second": string;
    }
    interface CYqh26f2wqv {
        "first": string;
        "second": string;
    }
    interface CYqhm4n9cvs {
        "first": string;
        "second": string;
    }
    interface CYrrzrz7kyr {
        "first": string;
        "second": string;
    }
    interface CZ81ftroqy1 {
        "first": string;
        "second": string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLC06u1uquy7pElement extends Components.C06u1uquy7p, HTMLStencilElement {
    }
    var HTMLC06u1uquy7pElement: {
        prototype: HTMLC06u1uquy7pElement;
        new (): HTMLC06u1uquy7pElement;
    };
    interface HTMLC07lxad0658Element extends Components.C07lxad0658, HTMLStencilElement {
    }
    var HTMLC07lxad0658Element: {
        prototype: HTMLC07lxad0658Element;
        new (): HTMLC07lxad0658Element;
    };
    interface HTMLC0zolhns0ttElement extends Components.C0zolhns0tt, HTMLStencilElement {
    }
    var HTMLC0zolhns0ttElement: {
        prototype: HTMLC0zolhns0ttElement;
        new (): HTMLC0zolhns0ttElement;
    };
    interface HTMLC1gfk4e7z6vElement extends Components.C1gfk4e7z6v, HTMLStencilElement {
    }
    var HTMLC1gfk4e7z6vElement: {
        prototype: HTMLC1gfk4e7z6vElement;
        new (): HTMLC1gfk4e7z6vElement;
    };
    interface HTMLC1zwn4ylwkgElement extends Components.C1zwn4ylwkg, HTMLStencilElement {
    }
    var HTMLC1zwn4ylwkgElement: {
        prototype: HTMLC1zwn4ylwkgElement;
        new (): HTMLC1zwn4ylwkgElement;
    };
    interface HTMLC2jdap6s83qElement extends Components.C2jdap6s83q, HTMLStencilElement {
    }
    var HTMLC2jdap6s83qElement: {
        prototype: HTMLC2jdap6s83qElement;
        new (): HTMLC2jdap6s83qElement;
    };
    interface HTMLC2l9zhv6s9jElement extends Components.C2l9zhv6s9j, HTMLStencilElement {
    }
    var HTMLC2l9zhv6s9jElement: {
        prototype: HTMLC2l9zhv6s9jElement;
        new (): HTMLC2l9zhv6s9jElement;
    };
    interface HTMLC372kixrse8Element extends Components.C372kixrse8, HTMLStencilElement {
    }
    var HTMLC372kixrse8Element: {
        prototype: HTMLC372kixrse8Element;
        new (): HTMLC372kixrse8Element;
    };
    interface HTMLC3b9k908rpkElement extends Components.C3b9k908rpk, HTMLStencilElement {
    }
    var HTMLC3b9k908rpkElement: {
        prototype: HTMLC3b9k908rpkElement;
        new (): HTMLC3b9k908rpkElement;
    };
    interface HTMLC3erd4s9c5mElement extends Components.C3erd4s9c5m, HTMLStencilElement {
    }
    var HTMLC3erd4s9c5mElement: {
        prototype: HTMLC3erd4s9c5mElement;
        new (): HTMLC3erd4s9c5mElement;
    };
    interface HTMLC3fxlqqoa1nElement extends Components.C3fxlqqoa1n, HTMLStencilElement {
    }
    var HTMLC3fxlqqoa1nElement: {
        prototype: HTMLC3fxlqqoa1nElement;
        new (): HTMLC3fxlqqoa1nElement;
    };
    interface HTMLC3in4zcw4irElement extends Components.C3in4zcw4ir, HTMLStencilElement {
    }
    var HTMLC3in4zcw4irElement: {
        prototype: HTMLC3in4zcw4irElement;
        new (): HTMLC3in4zcw4irElement;
    };
    interface HTMLC41k1do1hz9Element extends Components.C41k1do1hz9, HTMLStencilElement {
    }
    var HTMLC41k1do1hz9Element: {
        prototype: HTMLC41k1do1hz9Element;
        new (): HTMLC41k1do1hz9Element;
    };
    interface HTMLC4ec5vavagnElement extends Components.C4ec5vavagn, HTMLStencilElement {
    }
    var HTMLC4ec5vavagnElement: {
        prototype: HTMLC4ec5vavagnElement;
        new (): HTMLC4ec5vavagnElement;
    };
    interface HTMLC4fbygxj908Element extends Components.C4fbygxj908, HTMLStencilElement {
    }
    var HTMLC4fbygxj908Element: {
        prototype: HTMLC4fbygxj908Element;
        new (): HTMLC4fbygxj908Element;
    };
    interface HTMLC4y3ufy0vqzElement extends Components.C4y3ufy0vqz, HTMLStencilElement {
    }
    var HTMLC4y3ufy0vqzElement: {
        prototype: HTMLC4y3ufy0vqzElement;
        new (): HTMLC4y3ufy0vqzElement;
    };
    interface HTMLC5a0ubhr3nfElement extends Components.C5a0ubhr3nf, HTMLStencilElement {
    }
    var HTMLC5a0ubhr3nfElement: {
        prototype: HTMLC5a0ubhr3nfElement;
        new (): HTMLC5a0ubhr3nfElement;
    };
    interface HTMLC5cgko9z7rsElement extends Components.C5cgko9z7rs, HTMLStencilElement {
    }
    var HTMLC5cgko9z7rsElement: {
        prototype: HTMLC5cgko9z7rsElement;
        new (): HTMLC5cgko9z7rsElement;
    };
    interface HTMLC5fluomxfuaElement extends Components.C5fluomxfua, HTMLStencilElement {
    }
    var HTMLC5fluomxfuaElement: {
        prototype: HTMLC5fluomxfuaElement;
        new (): HTMLC5fluomxfuaElement;
    };
    interface HTMLC5gzkl3ag53Element extends Components.C5gzkl3ag53, HTMLStencilElement {
    }
    var HTMLC5gzkl3ag53Element: {
        prototype: HTMLC5gzkl3ag53Element;
        new (): HTMLC5gzkl3ag53Element;
    };
    interface HTMLC624g6590jzElement extends Components.C624g6590jz, HTMLStencilElement {
    }
    var HTMLC624g6590jzElement: {
        prototype: HTMLC624g6590jzElement;
        new (): HTMLC624g6590jzElement;
    };
    interface HTMLC6rlfmr7imiElement extends Components.C6rlfmr7imi, HTMLStencilElement {
    }
    var HTMLC6rlfmr7imiElement: {
        prototype: HTMLC6rlfmr7imiElement;
        new (): HTMLC6rlfmr7imiElement;
    };
    interface HTMLC7tix3ilvdyElement extends Components.C7tix3ilvdy, HTMLStencilElement {
    }
    var HTMLC7tix3ilvdyElement: {
        prototype: HTMLC7tix3ilvdyElement;
        new (): HTMLC7tix3ilvdyElement;
    };
    interface HTMLC8q2higyiy1Element extends Components.C8q2higyiy1, HTMLStencilElement {
    }
    var HTMLC8q2higyiy1Element: {
        prototype: HTMLC8q2higyiy1Element;
        new (): HTMLC8q2higyiy1Element;
    };
    interface HTMLC8z9htpdbrcElement extends Components.C8z9htpdbrc, HTMLStencilElement {
    }
    var HTMLC8z9htpdbrcElement: {
        prototype: HTMLC8z9htpdbrcElement;
        new (): HTMLC8z9htpdbrcElement;
    };
    interface HTMLC9h0bigfpssElement extends Components.C9h0bigfpss, HTMLStencilElement {
    }
    var HTMLC9h0bigfpssElement: {
        prototype: HTMLC9h0bigfpssElement;
        new (): HTMLC9h0bigfpssElement;
    };
    interface HTMLC9jv0q451duElement extends Components.C9jv0q451du, HTMLStencilElement {
    }
    var HTMLC9jv0q451duElement: {
        prototype: HTMLC9jv0q451duElement;
        new (): HTMLC9jv0q451duElement;
    };
    interface HTMLC9mzb3ftkciElement extends Components.C9mzb3ftkci, HTMLStencilElement {
    }
    var HTMLC9mzb3ftkciElement: {
        prototype: HTMLC9mzb3ftkciElement;
        new (): HTMLC9mzb3ftkciElement;
    };
    interface HTMLCArbrgx9up2Element extends Components.CArbrgx9up2, HTMLStencilElement {
    }
    var HTMLCArbrgx9up2Element: {
        prototype: HTMLCArbrgx9up2Element;
        new (): HTMLCArbrgx9up2Element;
    };
    interface HTMLCAu912e51ttElement extends Components.CAu912e51tt, HTMLStencilElement {
    }
    var HTMLCAu912e51ttElement: {
        prototype: HTMLCAu912e51ttElement;
        new (): HTMLCAu912e51ttElement;
    };
    interface HTMLCBqgp5mgr24Element extends Components.CBqgp5mgr24, HTMLStencilElement {
    }
    var HTMLCBqgp5mgr24Element: {
        prototype: HTMLCBqgp5mgr24Element;
        new (): HTMLCBqgp5mgr24Element;
    };
    interface HTMLCBzkrwx38iyElement extends Components.CBzkrwx38iy, HTMLStencilElement {
    }
    var HTMLCBzkrwx38iyElement: {
        prototype: HTMLCBzkrwx38iyElement;
        new (): HTMLCBzkrwx38iyElement;
    };
    interface HTMLCBzn7pzxw81Element extends Components.CBzn7pzxw81, HTMLStencilElement {
    }
    var HTMLCBzn7pzxw81Element: {
        prototype: HTMLCBzn7pzxw81Element;
        new (): HTMLCBzn7pzxw81Element;
    };
    interface HTMLCC75lozb961Element extends Components.CC75lozb961, HTMLStencilElement {
    }
    var HTMLCC75lozb961Element: {
        prototype: HTMLCC75lozb961Element;
        new (): HTMLCC75lozb961Element;
    };
    interface HTMLCC7c5t54urqElement extends Components.CC7c5t54urq, HTMLStencilElement {
    }
    var HTMLCC7c5t54urqElement: {
        prototype: HTMLCC7c5t54urqElement;
        new (): HTMLCC7c5t54urqElement;
    };
    interface HTMLCD7k6npd91eElement extends Components.CD7k6npd91e, HTMLStencilElement {
    }
    var HTMLCD7k6npd91eElement: {
        prototype: HTMLCD7k6npd91eElement;
        new (): HTMLCD7k6npd91eElement;
    };
    interface HTMLCDg1o6hvgmhElement extends Components.CDg1o6hvgmh, HTMLStencilElement {
    }
    var HTMLCDg1o6hvgmhElement: {
        prototype: HTMLCDg1o6hvgmhElement;
        new (): HTMLCDg1o6hvgmhElement;
    };
    interface HTMLCDg3pa9wx90Element extends Components.CDg3pa9wx90, HTMLStencilElement {
    }
    var HTMLCDg3pa9wx90Element: {
        prototype: HTMLCDg3pa9wx90Element;
        new (): HTMLCDg3pa9wx90Element;
    };
    interface HTMLCDw5fah0dakElement extends Components.CDw5fah0dak, HTMLStencilElement {
    }
    var HTMLCDw5fah0dakElement: {
        prototype: HTMLCDw5fah0dakElement;
        new (): HTMLCDw5fah0dakElement;
    };
    interface HTMLCEa6dkc7txrElement extends Components.CEa6dkc7txr, HTMLStencilElement {
    }
    var HTMLCEa6dkc7txrElement: {
        prototype: HTMLCEa6dkc7txrElement;
        new (): HTMLCEa6dkc7txrElement;
    };
    interface HTMLCEsoi0j8qe9Element extends Components.CEsoi0j8qe9, HTMLStencilElement {
    }
    var HTMLCEsoi0j8qe9Element: {
        prototype: HTMLCEsoi0j8qe9Element;
        new (): HTMLCEsoi0j8qe9Element;
    };
    interface HTMLCG9ehgvurflElement extends Components.CG9ehgvurfl, HTMLStencilElement {
    }
    var HTMLCG9ehgvurflElement: {
        prototype: HTMLCG9ehgvurflElement;
        new (): HTMLCG9ehgvurflElement;
    };
    interface HTMLCGxdiszlvbrElement extends Components.CGxdiszlvbr, HTMLStencilElement {
    }
    var HTMLCGxdiszlvbrElement: {
        prototype: HTMLCGxdiszlvbrElement;
        new (): HTMLCGxdiszlvbrElement;
    };
    interface HTMLCHynos1l9j1Element extends Components.CHynos1l9j1, HTMLStencilElement {
    }
    var HTMLCHynos1l9j1Element: {
        prototype: HTMLCHynos1l9j1Element;
        new (): HTMLCHynos1l9j1Element;
    };
    interface HTMLCI3u6qvb857Element extends Components.CI3u6qvb857, HTMLStencilElement {
    }
    var HTMLCI3u6qvb857Element: {
        prototype: HTMLCI3u6qvb857Element;
        new (): HTMLCI3u6qvb857Element;
    };
    interface HTMLCImh9k2bdv0Element extends Components.CImh9k2bdv0, HTMLStencilElement {
    }
    var HTMLCImh9k2bdv0Element: {
        prototype: HTMLCImh9k2bdv0Element;
        new (): HTMLCImh9k2bdv0Element;
    };
    interface HTMLCImtn3aobsiElement extends Components.CImtn3aobsi, HTMLStencilElement {
    }
    var HTMLCImtn3aobsiElement: {
        prototype: HTMLCImtn3aobsiElement;
        new (): HTMLCImtn3aobsiElement;
    };
    interface HTMLCIrlw1y0vnnElement extends Components.CIrlw1y0vnn, HTMLStencilElement {
    }
    var HTMLCIrlw1y0vnnElement: {
        prototype: HTMLCIrlw1y0vnnElement;
        new (): HTMLCIrlw1y0vnnElement;
    };
    interface HTMLCIsmiutkdb3Element extends Components.CIsmiutkdb3, HTMLStencilElement {
    }
    var HTMLCIsmiutkdb3Element: {
        prototype: HTMLCIsmiutkdb3Element;
        new (): HTMLCIsmiutkdb3Element;
    };
    interface HTMLCJdqsj6bhufElement extends Components.CJdqsj6bhuf, HTMLStencilElement {
    }
    var HTMLCJdqsj6bhufElement: {
        prototype: HTMLCJdqsj6bhufElement;
        new (): HTMLCJdqsj6bhufElement;
    };
    interface HTMLCJhossdpdsaElement extends Components.CJhossdpdsa, HTMLStencilElement {
    }
    var HTMLCJhossdpdsaElement: {
        prototype: HTMLCJhossdpdsaElement;
        new (): HTMLCJhossdpdsaElement;
    };
    interface HTMLCKjuy16vwnhElement extends Components.CKjuy16vwnh, HTMLStencilElement {
    }
    var HTMLCKjuy16vwnhElement: {
        prototype: HTMLCKjuy16vwnhElement;
        new (): HTMLCKjuy16vwnhElement;
    };
    interface HTMLCKxgdbgnyigElement extends Components.CKxgdbgnyig, HTMLStencilElement {
    }
    var HTMLCKxgdbgnyigElement: {
        prototype: HTMLCKxgdbgnyigElement;
        new (): HTMLCKxgdbgnyigElement;
    };
    interface HTMLCKyhxkza3bjElement extends Components.CKyhxkza3bj, HTMLStencilElement {
    }
    var HTMLCKyhxkza3bjElement: {
        prototype: HTMLCKyhxkza3bjElement;
        new (): HTMLCKyhxkza3bjElement;
    };
    interface HTMLCMac32hasu5Element extends Components.CMac32hasu5, HTMLStencilElement {
    }
    var HTMLCMac32hasu5Element: {
        prototype: HTMLCMac32hasu5Element;
        new (): HTMLCMac32hasu5Element;
    };
    interface HTMLCMhxod1mfr1Element extends Components.CMhxod1mfr1, HTMLStencilElement {
    }
    var HTMLCMhxod1mfr1Element: {
        prototype: HTMLCMhxod1mfr1Element;
        new (): HTMLCMhxod1mfr1Element;
    };
    interface HTMLCMyiojn1a6dElement extends Components.CMyiojn1a6d, HTMLStencilElement {
    }
    var HTMLCMyiojn1a6dElement: {
        prototype: HTMLCMyiojn1a6dElement;
        new (): HTMLCMyiojn1a6dElement;
    };
    interface HTMLCN58v98xjdjElement extends Components.CN58v98xjdj, HTMLStencilElement {
    }
    var HTMLCN58v98xjdjElement: {
        prototype: HTMLCN58v98xjdjElement;
        new (): HTMLCN58v98xjdjElement;
    };
    interface HTMLCN7a4ihuwatElement extends Components.CN7a4ihuwat, HTMLStencilElement {
    }
    var HTMLCN7a4ihuwatElement: {
        prototype: HTMLCN7a4ihuwatElement;
        new (): HTMLCN7a4ihuwatElement;
    };
    interface HTMLCNazayymwp9Element extends Components.CNazayymwp9, HTMLStencilElement {
    }
    var HTMLCNazayymwp9Element: {
        prototype: HTMLCNazayymwp9Element;
        new (): HTMLCNazayymwp9Element;
    };
    interface HTMLCNl8zpsalidElement extends Components.CNl8zpsalid, HTMLStencilElement {
    }
    var HTMLCNl8zpsalidElement: {
        prototype: HTMLCNl8zpsalidElement;
        new (): HTMLCNl8zpsalidElement;
    };
    interface HTMLCNor5t0g9doElement extends Components.CNor5t0g9do, HTMLStencilElement {
    }
    var HTMLCNor5t0g9doElement: {
        prototype: HTMLCNor5t0g9doElement;
        new (): HTMLCNor5t0g9doElement;
    };
    interface HTMLCNtciy01o41Element extends Components.CNtciy01o41, HTMLStencilElement {
    }
    var HTMLCNtciy01o41Element: {
        prototype: HTMLCNtciy01o41Element;
        new (): HTMLCNtciy01o41Element;
    };
    interface HTMLCOdvbf8zr05Element extends Components.COdvbf8zr05, HTMLStencilElement {
    }
    var HTMLCOdvbf8zr05Element: {
        prototype: HTMLCOdvbf8zr05Element;
        new (): HTMLCOdvbf8zr05Element;
    };
    interface HTMLCPma0x0hadnElement extends Components.CPma0x0hadn, HTMLStencilElement {
    }
    var HTMLCPma0x0hadnElement: {
        prototype: HTMLCPma0x0hadnElement;
        new (): HTMLCPma0x0hadnElement;
    };
    interface HTMLCPpqmrgr9urElement extends Components.CPpqmrgr9ur, HTMLStencilElement {
    }
    var HTMLCPpqmrgr9urElement: {
        prototype: HTMLCPpqmrgr9urElement;
        new (): HTMLCPpqmrgr9urElement;
    };
    interface HTMLCQ8olsms93hElement extends Components.CQ8olsms93h, HTMLStencilElement {
    }
    var HTMLCQ8olsms93hElement: {
        prototype: HTMLCQ8olsms93hElement;
        new (): HTMLCQ8olsms93hElement;
    };
    interface HTMLCQr0nl8jymdElement extends Components.CQr0nl8jymd, HTMLStencilElement {
    }
    var HTMLCQr0nl8jymdElement: {
        prototype: HTMLCQr0nl8jymdElement;
        new (): HTMLCQr0nl8jymdElement;
    };
    interface HTMLCR77lnek7x1Element extends Components.CR77lnek7x1, HTMLStencilElement {
    }
    var HTMLCR77lnek7x1Element: {
        prototype: HTMLCR77lnek7x1Element;
        new (): HTMLCR77lnek7x1Element;
    };
    interface HTMLCRda8pdtf5uElement extends Components.CRda8pdtf5u, HTMLStencilElement {
    }
    var HTMLCRda8pdtf5uElement: {
        prototype: HTMLCRda8pdtf5uElement;
        new (): HTMLCRda8pdtf5uElement;
    };
    interface HTMLCRkzbq12k0vElement extends Components.CRkzbq12k0v, HTMLStencilElement {
    }
    var HTMLCRkzbq12k0vElement: {
        prototype: HTMLCRkzbq12k0vElement;
        new (): HTMLCRkzbq12k0vElement;
    };
    interface HTMLCRuweknhd3aElement extends Components.CRuweknhd3a, HTMLStencilElement {
    }
    var HTMLCRuweknhd3aElement: {
        prototype: HTMLCRuweknhd3aElement;
        new (): HTMLCRuweknhd3aElement;
    };
    interface HTMLCS9tevpt81qElement extends Components.CS9tevpt81q, HTMLStencilElement {
    }
    var HTMLCS9tevpt81qElement: {
        prototype: HTMLCS9tevpt81qElement;
        new (): HTMLCS9tevpt81qElement;
    };
    interface HTMLCSc5u2i9fzdElement extends Components.CSc5u2i9fzd, HTMLStencilElement {
    }
    var HTMLCSc5u2i9fzdElement: {
        prototype: HTMLCSc5u2i9fzdElement;
        new (): HTMLCSc5u2i9fzdElement;
    };
    interface HTMLCSp4ik5bs8nElement extends Components.CSp4ik5bs8n, HTMLStencilElement {
    }
    var HTMLCSp4ik5bs8nElement: {
        prototype: HTMLCSp4ik5bs8nElement;
        new (): HTMLCSp4ik5bs8nElement;
    };
    interface HTMLCSv84ghh89rElement extends Components.CSv84ghh89r, HTMLStencilElement {
    }
    var HTMLCSv84ghh89rElement: {
        prototype: HTMLCSv84ghh89rElement;
        new (): HTMLCSv84ghh89rElement;
    };
    interface HTMLCTlafahtx59Element extends Components.CTlafahtx59, HTMLStencilElement {
    }
    var HTMLCTlafahtx59Element: {
        prototype: HTMLCTlafahtx59Element;
        new (): HTMLCTlafahtx59Element;
    };
    interface HTMLCTp8smsoy1tElement extends Components.CTp8smsoy1t, HTMLStencilElement {
    }
    var HTMLCTp8smsoy1tElement: {
        prototype: HTMLCTp8smsoy1tElement;
        new (): HTMLCTp8smsoy1tElement;
    };
    interface HTMLCTqm40gnm29Element extends Components.CTqm40gnm29, HTMLStencilElement {
    }
    var HTMLCTqm40gnm29Element: {
        prototype: HTMLCTqm40gnm29Element;
        new (): HTMLCTqm40gnm29Element;
    };
    interface HTMLCTz8loest3zElement extends Components.CTz8loest3z, HTMLStencilElement {
    }
    var HTMLCTz8loest3zElement: {
        prototype: HTMLCTz8loest3zElement;
        new (): HTMLCTz8loest3zElement;
    };
    interface HTMLCU24qr34bliElement extends Components.CU24qr34bli, HTMLStencilElement {
    }
    var HTMLCU24qr34bliElement: {
        prototype: HTMLCU24qr34bliElement;
        new (): HTMLCU24qr34bliElement;
    };
    interface HTMLCU4yltmxd3aElement extends Components.CU4yltmxd3a, HTMLStencilElement {
    }
    var HTMLCU4yltmxd3aElement: {
        prototype: HTMLCU4yltmxd3aElement;
        new (): HTMLCU4yltmxd3aElement;
    };
    interface HTMLCU5oftmd61cElement extends Components.CU5oftmd61c, HTMLStencilElement {
    }
    var HTMLCU5oftmd61cElement: {
        prototype: HTMLCU5oftmd61cElement;
        new (): HTMLCU5oftmd61cElement;
    };
    interface HTMLCUg8k83hoieElement extends Components.CUg8k83hoie, HTMLStencilElement {
    }
    var HTMLCUg8k83hoieElement: {
        prototype: HTMLCUg8k83hoieElement;
        new (): HTMLCUg8k83hoieElement;
    };
    interface HTMLCVgp19gz1ilElement extends Components.CVgp19gz1il, HTMLStencilElement {
    }
    var HTMLCVgp19gz1ilElement: {
        prototype: HTMLCVgp19gz1ilElement;
        new (): HTMLCVgp19gz1ilElement;
    };
    interface HTMLCVnn1j1of74Element extends Components.CVnn1j1of74, HTMLStencilElement {
    }
    var HTMLCVnn1j1of74Element: {
        prototype: HTMLCVnn1j1of74Element;
        new (): HTMLCVnn1j1of74Element;
    };
    interface HTMLCWa1wjxh046Element extends Components.CWa1wjxh046, HTMLStencilElement {
    }
    var HTMLCWa1wjxh046Element: {
        prototype: HTMLCWa1wjxh046Element;
        new (): HTMLCWa1wjxh046Element;
    };
    interface HTMLCWjoi1mwbs1Element extends Components.CWjoi1mwbs1, HTMLStencilElement {
    }
    var HTMLCWjoi1mwbs1Element: {
        prototype: HTMLCWjoi1mwbs1Element;
        new (): HTMLCWjoi1mwbs1Element;
    };
    interface HTMLCWn1p2nu3d5Element extends Components.CWn1p2nu3d5, HTMLStencilElement {
    }
    var HTMLCWn1p2nu3d5Element: {
        prototype: HTMLCWn1p2nu3d5Element;
        new (): HTMLCWn1p2nu3d5Element;
    };
    interface HTMLCWursvokoqdElement extends Components.CWursvokoqd, HTMLStencilElement {
    }
    var HTMLCWursvokoqdElement: {
        prototype: HTMLCWursvokoqdElement;
        new (): HTMLCWursvokoqdElement;
    };
    interface HTMLCXfj5pfjbzwElement extends Components.CXfj5pfjbzw, HTMLStencilElement {
    }
    var HTMLCXfj5pfjbzwElement: {
        prototype: HTMLCXfj5pfjbzwElement;
        new (): HTMLCXfj5pfjbzwElement;
    };
    interface HTMLCXm3sieu2i4Element extends Components.CXm3sieu2i4, HTMLStencilElement {
    }
    var HTMLCXm3sieu2i4Element: {
        prototype: HTMLCXm3sieu2i4Element;
        new (): HTMLCXm3sieu2i4Element;
    };
    interface HTMLCXvb7s33ex4Element extends Components.CXvb7s33ex4, HTMLStencilElement {
    }
    var HTMLCXvb7s33ex4Element: {
        prototype: HTMLCXvb7s33ex4Element;
        new (): HTMLCXvb7s33ex4Element;
    };
    interface HTMLCXw6voqzmdoElement extends Components.CXw6voqzmdo, HTMLStencilElement {
    }
    var HTMLCXw6voqzmdoElement: {
        prototype: HTMLCXw6voqzmdoElement;
        new (): HTMLCXw6voqzmdoElement;
    };
    interface HTMLCXxcxappzlcElement extends Components.CXxcxappzlc, HTMLStencilElement {
    }
    var HTMLCXxcxappzlcElement: {
        prototype: HTMLCXxcxappzlcElement;
        new (): HTMLCXxcxappzlcElement;
    };
    interface HTMLCYbsjy24fs9Element extends Components.CYbsjy24fs9, HTMLStencilElement {
    }
    var HTMLCYbsjy24fs9Element: {
        prototype: HTMLCYbsjy24fs9Element;
        new (): HTMLCYbsjy24fs9Element;
    };
    interface HTMLCYqh26f2wqvElement extends Components.CYqh26f2wqv, HTMLStencilElement {
    }
    var HTMLCYqh26f2wqvElement: {
        prototype: HTMLCYqh26f2wqvElement;
        new (): HTMLCYqh26f2wqvElement;
    };
    interface HTMLCYqhm4n9cvsElement extends Components.CYqhm4n9cvs, HTMLStencilElement {
    }
    var HTMLCYqhm4n9cvsElement: {
        prototype: HTMLCYqhm4n9cvsElement;
        new (): HTMLCYqhm4n9cvsElement;
    };
    interface HTMLCYrrzrz7kyrElement extends Components.CYrrzrz7kyr, HTMLStencilElement {
    }
    var HTMLCYrrzrz7kyrElement: {
        prototype: HTMLCYrrzrz7kyrElement;
        new (): HTMLCYrrzrz7kyrElement;
    };
    interface HTMLCZ81ftroqy1Element extends Components.CZ81ftroqy1, HTMLStencilElement {
    }
    var HTMLCZ81ftroqy1Element: {
        prototype: HTMLCZ81ftroqy1Element;
        new (): HTMLCZ81ftroqy1Element;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "c-06u1uquy7p": HTMLC06u1uquy7pElement;
        "c-07lxad0658": HTMLC07lxad0658Element;
        "c-0zolhns0tt": HTMLC0zolhns0ttElement;
        "c-1gfk4e7z6v": HTMLC1gfk4e7z6vElement;
        "c-1zwn4ylwkg": HTMLC1zwn4ylwkgElement;
        "c-2jdap6s83q": HTMLC2jdap6s83qElement;
        "c-2l9zhv6s9j": HTMLC2l9zhv6s9jElement;
        "c-372kixrse8": HTMLC372kixrse8Element;
        "c-3b9k908rpk": HTMLC3b9k908rpkElement;
        "c-3erd4s9c5m": HTMLC3erd4s9c5mElement;
        "c-3fxlqqoa1n": HTMLC3fxlqqoa1nElement;
        "c-3in4zcw4ir": HTMLC3in4zcw4irElement;
        "c-41k1do1hz9": HTMLC41k1do1hz9Element;
        "c-4ec5vavagn": HTMLC4ec5vavagnElement;
        "c-4fbygxj908": HTMLC4fbygxj908Element;
        "c-4y3ufy0vqz": HTMLC4y3ufy0vqzElement;
        "c-5a0ubhr3nf": HTMLC5a0ubhr3nfElement;
        "c-5cgko9z7rs": HTMLC5cgko9z7rsElement;
        "c-5fluomxfua": HTMLC5fluomxfuaElement;
        "c-5gzkl3ag53": HTMLC5gzkl3ag53Element;
        "c-624g6590jz": HTMLC624g6590jzElement;
        "c-6rlfmr7imi": HTMLC6rlfmr7imiElement;
        "c-7tix3ilvdy": HTMLC7tix3ilvdyElement;
        "c-8q2higyiy1": HTMLC8q2higyiy1Element;
        "c-8z9htpdbrc": HTMLC8z9htpdbrcElement;
        "c-9h0bigfpss": HTMLC9h0bigfpssElement;
        "c-9jv0q451du": HTMLC9jv0q451duElement;
        "c-9mzb3ftkci": HTMLC9mzb3ftkciElement;
        "c-arbrgx9up2": HTMLCArbrgx9up2Element;
        "c-au912e51tt": HTMLCAu912e51ttElement;
        "c-bqgp5mgr24": HTMLCBqgp5mgr24Element;
        "c-bzkrwx38iy": HTMLCBzkrwx38iyElement;
        "c-bzn7pzxw81": HTMLCBzn7pzxw81Element;
        "c-c75lozb961": HTMLCC75lozb961Element;
        "c-c7c5t54urq": HTMLCC7c5t54urqElement;
        "c-d7k6npd91e": HTMLCD7k6npd91eElement;
        "c-dg1o6hvgmh": HTMLCDg1o6hvgmhElement;
        "c-dg3pa9wx90": HTMLCDg3pa9wx90Element;
        "c-dw5fah0dak": HTMLCDw5fah0dakElement;
        "c-ea6dkc7txr": HTMLCEa6dkc7txrElement;
        "c-esoi0j8qe9": HTMLCEsoi0j8qe9Element;
        "c-g9ehgvurfl": HTMLCG9ehgvurflElement;
        "c-gxdiszlvbr": HTMLCGxdiszlvbrElement;
        "c-hynos1l9j1": HTMLCHynos1l9j1Element;
        "c-i3u6qvb857": HTMLCI3u6qvb857Element;
        "c-imh9k2bdv0": HTMLCImh9k2bdv0Element;
        "c-imtn3aobsi": HTMLCImtn3aobsiElement;
        "c-irlw1y0vnn": HTMLCIrlw1y0vnnElement;
        "c-ismiutkdb3": HTMLCIsmiutkdb3Element;
        "c-jdqsj6bhuf": HTMLCJdqsj6bhufElement;
        "c-jhossdpdsa": HTMLCJhossdpdsaElement;
        "c-kjuy16vwnh": HTMLCKjuy16vwnhElement;
        "c-kxgdbgnyig": HTMLCKxgdbgnyigElement;
        "c-kyhxkza3bj": HTMLCKyhxkza3bjElement;
        "c-mac32hasu5": HTMLCMac32hasu5Element;
        "c-mhxod1mfr1": HTMLCMhxod1mfr1Element;
        "c-myiojn1a6d": HTMLCMyiojn1a6dElement;
        "c-n58v98xjdj": HTMLCN58v98xjdjElement;
        "c-n7a4ihuwat": HTMLCN7a4ihuwatElement;
        "c-nazayymwp9": HTMLCNazayymwp9Element;
        "c-nl8zpsalid": HTMLCNl8zpsalidElement;
        "c-nor5t0g9do": HTMLCNor5t0g9doElement;
        "c-ntciy01o41": HTMLCNtciy01o41Element;
        "c-odvbf8zr05": HTMLCOdvbf8zr05Element;
        "c-pma0x0hadn": HTMLCPma0x0hadnElement;
        "c-ppqmrgr9ur": HTMLCPpqmrgr9urElement;
        "c-q8olsms93h": HTMLCQ8olsms93hElement;
        "c-qr0nl8jymd": HTMLCQr0nl8jymdElement;
        "c-r77lnek7x1": HTMLCR77lnek7x1Element;
        "c-rda8pdtf5u": HTMLCRda8pdtf5uElement;
        "c-rkzbq12k0v": HTMLCRkzbq12k0vElement;
        "c-ruweknhd3a": HTMLCRuweknhd3aElement;
        "c-s9tevpt81q": HTMLCS9tevpt81qElement;
        "c-sc5u2i9fzd": HTMLCSc5u2i9fzdElement;
        "c-sp4ik5bs8n": HTMLCSp4ik5bs8nElement;
        "c-sv84ghh89r": HTMLCSv84ghh89rElement;
        "c-tlafahtx59": HTMLCTlafahtx59Element;
        "c-tp8smsoy1t": HTMLCTp8smsoy1tElement;
        "c-tqm40gnm29": HTMLCTqm40gnm29Element;
        "c-tz8loest3z": HTMLCTz8loest3zElement;
        "c-u24qr34bli": HTMLCU24qr34bliElement;
        "c-u4yltmxd3a": HTMLCU4yltmxd3aElement;
        "c-u5oftmd61c": HTMLCU5oftmd61cElement;
        "c-ug8k83hoie": HTMLCUg8k83hoieElement;
        "c-vgp19gz1il": HTMLCVgp19gz1ilElement;
        "c-vnn1j1of74": HTMLCVnn1j1of74Element;
        "c-wa1wjxh046": HTMLCWa1wjxh046Element;
        "c-wjoi1mwbs1": HTMLCWjoi1mwbs1Element;
        "c-wn1p2nu3d5": HTMLCWn1p2nu3d5Element;
        "c-wursvokoqd": HTMLCWursvokoqdElement;
        "c-xfj5pfjbzw": HTMLCXfj5pfjbzwElement;
        "c-xm3sieu2i4": HTMLCXm3sieu2i4Element;
        "c-xvb7s33ex4": HTMLCXvb7s33ex4Element;
        "c-xw6voqzmdo": HTMLCXw6voqzmdoElement;
        "c-xxcxappzlc": HTMLCXxcxappzlcElement;
        "c-ybsjy24fs9": HTMLCYbsjy24fs9Element;
        "c-yqh26f2wqv": HTMLCYqh26f2wqvElement;
        "c-yqhm4n9cvs": HTMLCYqhm4n9cvsElement;
        "c-yrrzrz7kyr": HTMLCYrrzrz7kyrElement;
        "c-z81ftroqy1": HTMLCZ81ftroqy1Element;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface C06u1uquy7p {
        "first"?: string;
        "second"?: string;
    }
    interface C07lxad0658 {
        "first"?: string;
        "second"?: string;
    }
    interface C0zolhns0tt {
        "first"?: string;
        "second"?: string;
    }
    interface C1gfk4e7z6v {
        "first"?: string;
        "second"?: string;
    }
    interface C1zwn4ylwkg {
        "first"?: string;
        "second"?: string;
    }
    interface C2jdap6s83q {
        "first"?: string;
        "second"?: string;
    }
    interface C2l9zhv6s9j {
        "first"?: string;
        "second"?: string;
    }
    interface C372kixrse8 {
        "first"?: string;
        "second"?: string;
    }
    interface C3b9k908rpk {
        "first"?: string;
        "second"?: string;
    }
    interface C3erd4s9c5m {
        "first"?: string;
        "second"?: string;
    }
    interface C3fxlqqoa1n {
        "first"?: string;
        "second"?: string;
    }
    interface C3in4zcw4ir {
        "first"?: string;
        "second"?: string;
    }
    interface C41k1do1hz9 {
        "first"?: string;
        "second"?: string;
    }
    interface C4ec5vavagn {
        "first"?: string;
        "second"?: string;
    }
    interface C4fbygxj908 {
        "first"?: string;
        "second"?: string;
    }
    interface C4y3ufy0vqz {
        "first"?: string;
        "second"?: string;
    }
    interface C5a0ubhr3nf {
        "first"?: string;
        "second"?: string;
    }
    interface C5cgko9z7rs {
        "first"?: string;
        "second"?: string;
    }
    interface C5fluomxfua {
        "first"?: string;
        "second"?: string;
    }
    interface C5gzkl3ag53 {
        "first"?: string;
        "second"?: string;
    }
    interface C624g6590jz {
        "first"?: string;
        "second"?: string;
    }
    interface C6rlfmr7imi {
        "first"?: string;
        "second"?: string;
    }
    interface C7tix3ilvdy {
        "first"?: string;
        "second"?: string;
    }
    interface C8q2higyiy1 {
        "first"?: string;
        "second"?: string;
    }
    interface C8z9htpdbrc {
        "first"?: string;
        "second"?: string;
    }
    interface C9h0bigfpss {
        "first"?: string;
        "second"?: string;
    }
    interface C9jv0q451du {
        "first"?: string;
        "second"?: string;
    }
    interface C9mzb3ftkci {
        "first"?: string;
        "second"?: string;
    }
    interface CArbrgx9up2 {
        "first"?: string;
        "second"?: string;
    }
    interface CAu912e51tt {
        "first"?: string;
        "second"?: string;
    }
    interface CBqgp5mgr24 {
        "first"?: string;
        "second"?: string;
    }
    interface CBzkrwx38iy {
        "first"?: string;
        "second"?: string;
    }
    interface CBzn7pzxw81 {
        "first"?: string;
        "second"?: string;
    }
    interface CC75lozb961 {
        "first"?: string;
        "second"?: string;
    }
    interface CC7c5t54urq {
        "first"?: string;
        "second"?: string;
    }
    interface CD7k6npd91e {
        "first"?: string;
        "second"?: string;
    }
    interface CDg1o6hvgmh {
        "first"?: string;
        "second"?: string;
    }
    interface CDg3pa9wx90 {
        "first"?: string;
        "second"?: string;
    }
    interface CDw5fah0dak {
        "first"?: string;
        "second"?: string;
    }
    interface CEa6dkc7txr {
        "first"?: string;
        "second"?: string;
    }
    interface CEsoi0j8qe9 {
        "first"?: string;
        "second"?: string;
    }
    interface CG9ehgvurfl {
        "first"?: string;
        "second"?: string;
    }
    interface CGxdiszlvbr {
        "first"?: string;
        "second"?: string;
    }
    interface CHynos1l9j1 {
        "first"?: string;
        "second"?: string;
    }
    interface CI3u6qvb857 {
        "first"?: string;
        "second"?: string;
    }
    interface CImh9k2bdv0 {
        "first"?: string;
        "second"?: string;
    }
    interface CImtn3aobsi {
        "first"?: string;
        "second"?: string;
    }
    interface CIrlw1y0vnn {
        "first"?: string;
        "second"?: string;
    }
    interface CIsmiutkdb3 {
        "first"?: string;
        "second"?: string;
    }
    interface CJdqsj6bhuf {
        "first"?: string;
        "second"?: string;
    }
    interface CJhossdpdsa {
        "first"?: string;
        "second"?: string;
    }
    interface CKjuy16vwnh {
        "first"?: string;
        "second"?: string;
    }
    interface CKxgdbgnyig {
        "first"?: string;
        "second"?: string;
    }
    interface CKyhxkza3bj {
        "first"?: string;
        "second"?: string;
    }
    interface CMac32hasu5 {
        "first"?: string;
        "second"?: string;
    }
    interface CMhxod1mfr1 {
        "first"?: string;
        "second"?: string;
    }
    interface CMyiojn1a6d {
        "first"?: string;
        "second"?: string;
    }
    interface CN58v98xjdj {
        "first"?: string;
        "second"?: string;
    }
    interface CN7a4ihuwat {
        "first"?: string;
        "second"?: string;
    }
    interface CNazayymwp9 {
        "first"?: string;
        "second"?: string;
    }
    interface CNl8zpsalid {
        "first"?: string;
        "second"?: string;
    }
    interface CNor5t0g9do {
        "first"?: string;
        "second"?: string;
    }
    interface CNtciy01o41 {
        "first"?: string;
        "second"?: string;
    }
    interface COdvbf8zr05 {
        "first"?: string;
        "second"?: string;
    }
    interface CPma0x0hadn {
        "first"?: string;
        "second"?: string;
    }
    interface CPpqmrgr9ur {
        "first"?: string;
        "second"?: string;
    }
    interface CQ8olsms93h {
        "first"?: string;
        "second"?: string;
    }
    interface CQr0nl8jymd {
        "first"?: string;
        "second"?: string;
    }
    interface CR77lnek7x1 {
        "first"?: string;
        "second"?: string;
    }
    interface CRda8pdtf5u {
        "first"?: string;
        "second"?: string;
    }
    interface CRkzbq12k0v {
        "first"?: string;
        "second"?: string;
    }
    interface CRuweknhd3a {
        "first"?: string;
        "second"?: string;
    }
    interface CS9tevpt81q {
        "first"?: string;
        "second"?: string;
    }
    interface CSc5u2i9fzd {
        "first"?: string;
        "second"?: string;
    }
    interface CSp4ik5bs8n {
        "first"?: string;
        "second"?: string;
    }
    interface CSv84ghh89r {
        "first"?: string;
        "second"?: string;
    }
    interface CTlafahtx59 {
        "first"?: string;
        "second"?: string;
    }
    interface CTp8smsoy1t {
        "first"?: string;
        "second"?: string;
    }
    interface CTqm40gnm29 {
        "first"?: string;
        "second"?: string;
    }
    interface CTz8loest3z {
        "first"?: string;
        "second"?: string;
    }
    interface CU24qr34bli {
        "first"?: string;
        "second"?: string;
    }
    interface CU4yltmxd3a {
        "first"?: string;
        "second"?: string;
    }
    interface CU5oftmd61c {
        "first"?: string;
        "second"?: string;
    }
    interface CUg8k83hoie {
        "first"?: string;
        "second"?: string;
    }
    interface CVgp19gz1il {
        "first"?: string;
        "second"?: string;
    }
    interface CVnn1j1of74 {
        "first"?: string;
        "second"?: string;
    }
    interface CWa1wjxh046 {
        "first"?: string;
        "second"?: string;
    }
    interface CWjoi1mwbs1 {
        "first"?: string;
        "second"?: string;
    }
    interface CWn1p2nu3d5 {
        "first"?: string;
        "second"?: string;
    }
    interface CWursvokoqd {
        "first"?: string;
        "second"?: string;
    }
    interface CXfj5pfjbzw {
        "first"?: string;
        "second"?: string;
    }
    interface CXm3sieu2i4 {
        "first"?: string;
        "second"?: string;
    }
    interface CXvb7s33ex4 {
        "first"?: string;
        "second"?: string;
    }
    interface CXw6voqzmdo {
        "first"?: string;
        "second"?: string;
    }
    interface CXxcxappzlc {
        "first"?: string;
        "second"?: string;
    }
    interface CYbsjy24fs9 {
        "first"?: string;
        "second"?: string;
    }
    interface CYqh26f2wqv {
        "first"?: string;
        "second"?: string;
    }
    interface CYqhm4n9cvs {
        "first"?: string;
        "second"?: string;
    }
    interface CYrrzrz7kyr {
        "first"?: string;
        "second"?: string;
    }
    interface CZ81ftroqy1 {
        "first"?: string;
        "second"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "c-06u1uquy7p": C06u1uquy7p;
        "c-07lxad0658": C07lxad0658;
        "c-0zolhns0tt": C0zolhns0tt;
        "c-1gfk4e7z6v": C1gfk4e7z6v;
        "c-1zwn4ylwkg": C1zwn4ylwkg;
        "c-2jdap6s83q": C2jdap6s83q;
        "c-2l9zhv6s9j": C2l9zhv6s9j;
        "c-372kixrse8": C372kixrse8;
        "c-3b9k908rpk": C3b9k908rpk;
        "c-3erd4s9c5m": C3erd4s9c5m;
        "c-3fxlqqoa1n": C3fxlqqoa1n;
        "c-3in4zcw4ir": C3in4zcw4ir;
        "c-41k1do1hz9": C41k1do1hz9;
        "c-4ec5vavagn": C4ec5vavagn;
        "c-4fbygxj908": C4fbygxj908;
        "c-4y3ufy0vqz": C4y3ufy0vqz;
        "c-5a0ubhr3nf": C5a0ubhr3nf;
        "c-5cgko9z7rs": C5cgko9z7rs;
        "c-5fluomxfua": C5fluomxfua;
        "c-5gzkl3ag53": C5gzkl3ag53;
        "c-624g6590jz": C624g6590jz;
        "c-6rlfmr7imi": C6rlfmr7imi;
        "c-7tix3ilvdy": C7tix3ilvdy;
        "c-8q2higyiy1": C8q2higyiy1;
        "c-8z9htpdbrc": C8z9htpdbrc;
        "c-9h0bigfpss": C9h0bigfpss;
        "c-9jv0q451du": C9jv0q451du;
        "c-9mzb3ftkci": C9mzb3ftkci;
        "c-arbrgx9up2": CArbrgx9up2;
        "c-au912e51tt": CAu912e51tt;
        "c-bqgp5mgr24": CBqgp5mgr24;
        "c-bzkrwx38iy": CBzkrwx38iy;
        "c-bzn7pzxw81": CBzn7pzxw81;
        "c-c75lozb961": CC75lozb961;
        "c-c7c5t54urq": CC7c5t54urq;
        "c-d7k6npd91e": CD7k6npd91e;
        "c-dg1o6hvgmh": CDg1o6hvgmh;
        "c-dg3pa9wx90": CDg3pa9wx90;
        "c-dw5fah0dak": CDw5fah0dak;
        "c-ea6dkc7txr": CEa6dkc7txr;
        "c-esoi0j8qe9": CEsoi0j8qe9;
        "c-g9ehgvurfl": CG9ehgvurfl;
        "c-gxdiszlvbr": CGxdiszlvbr;
        "c-hynos1l9j1": CHynos1l9j1;
        "c-i3u6qvb857": CI3u6qvb857;
        "c-imh9k2bdv0": CImh9k2bdv0;
        "c-imtn3aobsi": CImtn3aobsi;
        "c-irlw1y0vnn": CIrlw1y0vnn;
        "c-ismiutkdb3": CIsmiutkdb3;
        "c-jdqsj6bhuf": CJdqsj6bhuf;
        "c-jhossdpdsa": CJhossdpdsa;
        "c-kjuy16vwnh": CKjuy16vwnh;
        "c-kxgdbgnyig": CKxgdbgnyig;
        "c-kyhxkza3bj": CKyhxkza3bj;
        "c-mac32hasu5": CMac32hasu5;
        "c-mhxod1mfr1": CMhxod1mfr1;
        "c-myiojn1a6d": CMyiojn1a6d;
        "c-n58v98xjdj": CN58v98xjdj;
        "c-n7a4ihuwat": CN7a4ihuwat;
        "c-nazayymwp9": CNazayymwp9;
        "c-nl8zpsalid": CNl8zpsalid;
        "c-nor5t0g9do": CNor5t0g9do;
        "c-ntciy01o41": CNtciy01o41;
        "c-odvbf8zr05": COdvbf8zr05;
        "c-pma0x0hadn": CPma0x0hadn;
        "c-ppqmrgr9ur": CPpqmrgr9ur;
        "c-q8olsms93h": CQ8olsms93h;
        "c-qr0nl8jymd": CQr0nl8jymd;
        "c-r77lnek7x1": CR77lnek7x1;
        "c-rda8pdtf5u": CRda8pdtf5u;
        "c-rkzbq12k0v": CRkzbq12k0v;
        "c-ruweknhd3a": CRuweknhd3a;
        "c-s9tevpt81q": CS9tevpt81q;
        "c-sc5u2i9fzd": CSc5u2i9fzd;
        "c-sp4ik5bs8n": CSp4ik5bs8n;
        "c-sv84ghh89r": CSv84ghh89r;
        "c-tlafahtx59": CTlafahtx59;
        "c-tp8smsoy1t": CTp8smsoy1t;
        "c-tqm40gnm29": CTqm40gnm29;
        "c-tz8loest3z": CTz8loest3z;
        "c-u24qr34bli": CU24qr34bli;
        "c-u4yltmxd3a": CU4yltmxd3a;
        "c-u5oftmd61c": CU5oftmd61c;
        "c-ug8k83hoie": CUg8k83hoie;
        "c-vgp19gz1il": CVgp19gz1il;
        "c-vnn1j1of74": CVnn1j1of74;
        "c-wa1wjxh046": CWa1wjxh046;
        "c-wjoi1mwbs1": CWjoi1mwbs1;
        "c-wn1p2nu3d5": CWn1p2nu3d5;
        "c-wursvokoqd": CWursvokoqd;
        "c-xfj5pfjbzw": CXfj5pfjbzw;
        "c-xm3sieu2i4": CXm3sieu2i4;
        "c-xvb7s33ex4": CXvb7s33ex4;
        "c-xw6voqzmdo": CXw6voqzmdo;
        "c-xxcxappzlc": CXxcxappzlc;
        "c-ybsjy24fs9": CYbsjy24fs9;
        "c-yqh26f2wqv": CYqh26f2wqv;
        "c-yqhm4n9cvs": CYqhm4n9cvs;
        "c-yrrzrz7kyr": CYrrzrz7kyr;
        "c-z81ftroqy1": CZ81ftroqy1;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "c-06u1uquy7p": LocalJSX.C06u1uquy7p & JSXBase.HTMLAttributes<HTMLC06u1uquy7pElement>;
            "c-07lxad0658": LocalJSX.C07lxad0658 & JSXBase.HTMLAttributes<HTMLC07lxad0658Element>;
            "c-0zolhns0tt": LocalJSX.C0zolhns0tt & JSXBase.HTMLAttributes<HTMLC0zolhns0ttElement>;
            "c-1gfk4e7z6v": LocalJSX.C1gfk4e7z6v & JSXBase.HTMLAttributes<HTMLC1gfk4e7z6vElement>;
            "c-1zwn4ylwkg": LocalJSX.C1zwn4ylwkg & JSXBase.HTMLAttributes<HTMLC1zwn4ylwkgElement>;
            "c-2jdap6s83q": LocalJSX.C2jdap6s83q & JSXBase.HTMLAttributes<HTMLC2jdap6s83qElement>;
            "c-2l9zhv6s9j": LocalJSX.C2l9zhv6s9j & JSXBase.HTMLAttributes<HTMLC2l9zhv6s9jElement>;
            "c-372kixrse8": LocalJSX.C372kixrse8 & JSXBase.HTMLAttributes<HTMLC372kixrse8Element>;
            "c-3b9k908rpk": LocalJSX.C3b9k908rpk & JSXBase.HTMLAttributes<HTMLC3b9k908rpkElement>;
            "c-3erd4s9c5m": LocalJSX.C3erd4s9c5m & JSXBase.HTMLAttributes<HTMLC3erd4s9c5mElement>;
            "c-3fxlqqoa1n": LocalJSX.C3fxlqqoa1n & JSXBase.HTMLAttributes<HTMLC3fxlqqoa1nElement>;
            "c-3in4zcw4ir": LocalJSX.C3in4zcw4ir & JSXBase.HTMLAttributes<HTMLC3in4zcw4irElement>;
            "c-41k1do1hz9": LocalJSX.C41k1do1hz9 & JSXBase.HTMLAttributes<HTMLC41k1do1hz9Element>;
            "c-4ec5vavagn": LocalJSX.C4ec5vavagn & JSXBase.HTMLAttributes<HTMLC4ec5vavagnElement>;
            "c-4fbygxj908": LocalJSX.C4fbygxj908 & JSXBase.HTMLAttributes<HTMLC4fbygxj908Element>;
            "c-4y3ufy0vqz": LocalJSX.C4y3ufy0vqz & JSXBase.HTMLAttributes<HTMLC4y3ufy0vqzElement>;
            "c-5a0ubhr3nf": LocalJSX.C5a0ubhr3nf & JSXBase.HTMLAttributes<HTMLC5a0ubhr3nfElement>;
            "c-5cgko9z7rs": LocalJSX.C5cgko9z7rs & JSXBase.HTMLAttributes<HTMLC5cgko9z7rsElement>;
            "c-5fluomxfua": LocalJSX.C5fluomxfua & JSXBase.HTMLAttributes<HTMLC5fluomxfuaElement>;
            "c-5gzkl3ag53": LocalJSX.C5gzkl3ag53 & JSXBase.HTMLAttributes<HTMLC5gzkl3ag53Element>;
            "c-624g6590jz": LocalJSX.C624g6590jz & JSXBase.HTMLAttributes<HTMLC624g6590jzElement>;
            "c-6rlfmr7imi": LocalJSX.C6rlfmr7imi & JSXBase.HTMLAttributes<HTMLC6rlfmr7imiElement>;
            "c-7tix3ilvdy": LocalJSX.C7tix3ilvdy & JSXBase.HTMLAttributes<HTMLC7tix3ilvdyElement>;
            "c-8q2higyiy1": LocalJSX.C8q2higyiy1 & JSXBase.HTMLAttributes<HTMLC8q2higyiy1Element>;
            "c-8z9htpdbrc": LocalJSX.C8z9htpdbrc & JSXBase.HTMLAttributes<HTMLC8z9htpdbrcElement>;
            "c-9h0bigfpss": LocalJSX.C9h0bigfpss & JSXBase.HTMLAttributes<HTMLC9h0bigfpssElement>;
            "c-9jv0q451du": LocalJSX.C9jv0q451du & JSXBase.HTMLAttributes<HTMLC9jv0q451duElement>;
            "c-9mzb3ftkci": LocalJSX.C9mzb3ftkci & JSXBase.HTMLAttributes<HTMLC9mzb3ftkciElement>;
            "c-arbrgx9up2": LocalJSX.CArbrgx9up2 & JSXBase.HTMLAttributes<HTMLCArbrgx9up2Element>;
            "c-au912e51tt": LocalJSX.CAu912e51tt & JSXBase.HTMLAttributes<HTMLCAu912e51ttElement>;
            "c-bqgp5mgr24": LocalJSX.CBqgp5mgr24 & JSXBase.HTMLAttributes<HTMLCBqgp5mgr24Element>;
            "c-bzkrwx38iy": LocalJSX.CBzkrwx38iy & JSXBase.HTMLAttributes<HTMLCBzkrwx38iyElement>;
            "c-bzn7pzxw81": LocalJSX.CBzn7pzxw81 & JSXBase.HTMLAttributes<HTMLCBzn7pzxw81Element>;
            "c-c75lozb961": LocalJSX.CC75lozb961 & JSXBase.HTMLAttributes<HTMLCC75lozb961Element>;
            "c-c7c5t54urq": LocalJSX.CC7c5t54urq & JSXBase.HTMLAttributes<HTMLCC7c5t54urqElement>;
            "c-d7k6npd91e": LocalJSX.CD7k6npd91e & JSXBase.HTMLAttributes<HTMLCD7k6npd91eElement>;
            "c-dg1o6hvgmh": LocalJSX.CDg1o6hvgmh & JSXBase.HTMLAttributes<HTMLCDg1o6hvgmhElement>;
            "c-dg3pa9wx90": LocalJSX.CDg3pa9wx90 & JSXBase.HTMLAttributes<HTMLCDg3pa9wx90Element>;
            "c-dw5fah0dak": LocalJSX.CDw5fah0dak & JSXBase.HTMLAttributes<HTMLCDw5fah0dakElement>;
            "c-ea6dkc7txr": LocalJSX.CEa6dkc7txr & JSXBase.HTMLAttributes<HTMLCEa6dkc7txrElement>;
            "c-esoi0j8qe9": LocalJSX.CEsoi0j8qe9 & JSXBase.HTMLAttributes<HTMLCEsoi0j8qe9Element>;
            "c-g9ehgvurfl": LocalJSX.CG9ehgvurfl & JSXBase.HTMLAttributes<HTMLCG9ehgvurflElement>;
            "c-gxdiszlvbr": LocalJSX.CGxdiszlvbr & JSXBase.HTMLAttributes<HTMLCGxdiszlvbrElement>;
            "c-hynos1l9j1": LocalJSX.CHynos1l9j1 & JSXBase.HTMLAttributes<HTMLCHynos1l9j1Element>;
            "c-i3u6qvb857": LocalJSX.CI3u6qvb857 & JSXBase.HTMLAttributes<HTMLCI3u6qvb857Element>;
            "c-imh9k2bdv0": LocalJSX.CImh9k2bdv0 & JSXBase.HTMLAttributes<HTMLCImh9k2bdv0Element>;
            "c-imtn3aobsi": LocalJSX.CImtn3aobsi & JSXBase.HTMLAttributes<HTMLCImtn3aobsiElement>;
            "c-irlw1y0vnn": LocalJSX.CIrlw1y0vnn & JSXBase.HTMLAttributes<HTMLCIrlw1y0vnnElement>;
            "c-ismiutkdb3": LocalJSX.CIsmiutkdb3 & JSXBase.HTMLAttributes<HTMLCIsmiutkdb3Element>;
            "c-jdqsj6bhuf": LocalJSX.CJdqsj6bhuf & JSXBase.HTMLAttributes<HTMLCJdqsj6bhufElement>;
            "c-jhossdpdsa": LocalJSX.CJhossdpdsa & JSXBase.HTMLAttributes<HTMLCJhossdpdsaElement>;
            "c-kjuy16vwnh": LocalJSX.CKjuy16vwnh & JSXBase.HTMLAttributes<HTMLCKjuy16vwnhElement>;
            "c-kxgdbgnyig": LocalJSX.CKxgdbgnyig & JSXBase.HTMLAttributes<HTMLCKxgdbgnyigElement>;
            "c-kyhxkza3bj": LocalJSX.CKyhxkza3bj & JSXBase.HTMLAttributes<HTMLCKyhxkza3bjElement>;
            "c-mac32hasu5": LocalJSX.CMac32hasu5 & JSXBase.HTMLAttributes<HTMLCMac32hasu5Element>;
            "c-mhxod1mfr1": LocalJSX.CMhxod1mfr1 & JSXBase.HTMLAttributes<HTMLCMhxod1mfr1Element>;
            "c-myiojn1a6d": LocalJSX.CMyiojn1a6d & JSXBase.HTMLAttributes<HTMLCMyiojn1a6dElement>;
            "c-n58v98xjdj": LocalJSX.CN58v98xjdj & JSXBase.HTMLAttributes<HTMLCN58v98xjdjElement>;
            "c-n7a4ihuwat": LocalJSX.CN7a4ihuwat & JSXBase.HTMLAttributes<HTMLCN7a4ihuwatElement>;
            "c-nazayymwp9": LocalJSX.CNazayymwp9 & JSXBase.HTMLAttributes<HTMLCNazayymwp9Element>;
            "c-nl8zpsalid": LocalJSX.CNl8zpsalid & JSXBase.HTMLAttributes<HTMLCNl8zpsalidElement>;
            "c-nor5t0g9do": LocalJSX.CNor5t0g9do & JSXBase.HTMLAttributes<HTMLCNor5t0g9doElement>;
            "c-ntciy01o41": LocalJSX.CNtciy01o41 & JSXBase.HTMLAttributes<HTMLCNtciy01o41Element>;
            "c-odvbf8zr05": LocalJSX.COdvbf8zr05 & JSXBase.HTMLAttributes<HTMLCOdvbf8zr05Element>;
            "c-pma0x0hadn": LocalJSX.CPma0x0hadn & JSXBase.HTMLAttributes<HTMLCPma0x0hadnElement>;
            "c-ppqmrgr9ur": LocalJSX.CPpqmrgr9ur & JSXBase.HTMLAttributes<HTMLCPpqmrgr9urElement>;
            "c-q8olsms93h": LocalJSX.CQ8olsms93h & JSXBase.HTMLAttributes<HTMLCQ8olsms93hElement>;
            "c-qr0nl8jymd": LocalJSX.CQr0nl8jymd & JSXBase.HTMLAttributes<HTMLCQr0nl8jymdElement>;
            "c-r77lnek7x1": LocalJSX.CR77lnek7x1 & JSXBase.HTMLAttributes<HTMLCR77lnek7x1Element>;
            "c-rda8pdtf5u": LocalJSX.CRda8pdtf5u & JSXBase.HTMLAttributes<HTMLCRda8pdtf5uElement>;
            "c-rkzbq12k0v": LocalJSX.CRkzbq12k0v & JSXBase.HTMLAttributes<HTMLCRkzbq12k0vElement>;
            "c-ruweknhd3a": LocalJSX.CRuweknhd3a & JSXBase.HTMLAttributes<HTMLCRuweknhd3aElement>;
            "c-s9tevpt81q": LocalJSX.CS9tevpt81q & JSXBase.HTMLAttributes<HTMLCS9tevpt81qElement>;
            "c-sc5u2i9fzd": LocalJSX.CSc5u2i9fzd & JSXBase.HTMLAttributes<HTMLCSc5u2i9fzdElement>;
            "c-sp4ik5bs8n": LocalJSX.CSp4ik5bs8n & JSXBase.HTMLAttributes<HTMLCSp4ik5bs8nElement>;
            "c-sv84ghh89r": LocalJSX.CSv84ghh89r & JSXBase.HTMLAttributes<HTMLCSv84ghh89rElement>;
            "c-tlafahtx59": LocalJSX.CTlafahtx59 & JSXBase.HTMLAttributes<HTMLCTlafahtx59Element>;
            "c-tp8smsoy1t": LocalJSX.CTp8smsoy1t & JSXBase.HTMLAttributes<HTMLCTp8smsoy1tElement>;
            "c-tqm40gnm29": LocalJSX.CTqm40gnm29 & JSXBase.HTMLAttributes<HTMLCTqm40gnm29Element>;
            "c-tz8loest3z": LocalJSX.CTz8loest3z & JSXBase.HTMLAttributes<HTMLCTz8loest3zElement>;
            "c-u24qr34bli": LocalJSX.CU24qr34bli & JSXBase.HTMLAttributes<HTMLCU24qr34bliElement>;
            "c-u4yltmxd3a": LocalJSX.CU4yltmxd3a & JSXBase.HTMLAttributes<HTMLCU4yltmxd3aElement>;
            "c-u5oftmd61c": LocalJSX.CU5oftmd61c & JSXBase.HTMLAttributes<HTMLCU5oftmd61cElement>;
            "c-ug8k83hoie": LocalJSX.CUg8k83hoie & JSXBase.HTMLAttributes<HTMLCUg8k83hoieElement>;
            "c-vgp19gz1il": LocalJSX.CVgp19gz1il & JSXBase.HTMLAttributes<HTMLCVgp19gz1ilElement>;
            "c-vnn1j1of74": LocalJSX.CVnn1j1of74 & JSXBase.HTMLAttributes<HTMLCVnn1j1of74Element>;
            "c-wa1wjxh046": LocalJSX.CWa1wjxh046 & JSXBase.HTMLAttributes<HTMLCWa1wjxh046Element>;
            "c-wjoi1mwbs1": LocalJSX.CWjoi1mwbs1 & JSXBase.HTMLAttributes<HTMLCWjoi1mwbs1Element>;
            "c-wn1p2nu3d5": LocalJSX.CWn1p2nu3d5 & JSXBase.HTMLAttributes<HTMLCWn1p2nu3d5Element>;
            "c-wursvokoqd": LocalJSX.CWursvokoqd & JSXBase.HTMLAttributes<HTMLCWursvokoqdElement>;
            "c-xfj5pfjbzw": LocalJSX.CXfj5pfjbzw & JSXBase.HTMLAttributes<HTMLCXfj5pfjbzwElement>;
            "c-xm3sieu2i4": LocalJSX.CXm3sieu2i4 & JSXBase.HTMLAttributes<HTMLCXm3sieu2i4Element>;
            "c-xvb7s33ex4": LocalJSX.CXvb7s33ex4 & JSXBase.HTMLAttributes<HTMLCXvb7s33ex4Element>;
            "c-xw6voqzmdo": LocalJSX.CXw6voqzmdo & JSXBase.HTMLAttributes<HTMLCXw6voqzmdoElement>;
            "c-xxcxappzlc": LocalJSX.CXxcxappzlc & JSXBase.HTMLAttributes<HTMLCXxcxappzlcElement>;
            "c-ybsjy24fs9": LocalJSX.CYbsjy24fs9 & JSXBase.HTMLAttributes<HTMLCYbsjy24fs9Element>;
            "c-yqh26f2wqv": LocalJSX.CYqh26f2wqv & JSXBase.HTMLAttributes<HTMLCYqh26f2wqvElement>;
            "c-yqhm4n9cvs": LocalJSX.CYqhm4n9cvs & JSXBase.HTMLAttributes<HTMLCYqhm4n9cvsElement>;
            "c-yrrzrz7kyr": LocalJSX.CYrrzrz7kyr & JSXBase.HTMLAttributes<HTMLCYrrzrz7kyrElement>;
            "c-z81ftroqy1": LocalJSX.CZ81ftroqy1 & JSXBase.HTMLAttributes<HTMLCZ81ftroqy1Element>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
